plugins {
    id "architectury-plugin" version "3.5.166"
    id "dev.architectury.loom" version "1.14.473" apply false
    id "com.gradleup.shadow" version "9.4.1" apply false
    id "idea"
}

tasks.named("wrapper", Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

architectury {
    minecraft = rootProject.minecraft_version
}

subprojects {
    plugins.withId("dev.architectury.loom") {
        loom {
            silentMojangMappingsLicense()
        }

        dependencies {
            minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
            mappings loom.officialMojangMappings()
        }
    }
}

allprojects {
    apply plugin: "java-library"
    apply plugin: "architectury-plugin"
    apply plugin: "maven-publish"

    group = rootProject.maven_group
    version = rootProject.mod_version

    base {
        archivesName = rootProject.mod_id
    }

    repositories {
        if (rootProject.useLocalToucanLib.toBoolean()) {
            mavenLocal()
        }

        mavenCentral()
        maven { url = uri("https://maven.architectury.dev/") }
        maven { url = uri("https://maven.fabricmc.net/") }
        maven { url = uri("https://maven.terraformersmc.com/") }
        maven { url = uri("https://maven.ladysnake.org/releases") }
        maven { url = uri("https://maven.neoforged.net/releases/") }

        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = uri("https://api.modrinth.com/maven")
                }
            }
            filter {
                includeGroup "maven.modrinth"
            }
        }

        exclusiveContent {
            forRepository {
                maven {
                    name = "CurseMaven"
                    url = uri("https://cursemaven.com/")
                }
            }
            filter {
                includeGroup "curse.maven"
            }
        }
    }

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(rootProject.java_version.toInteger())
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = rootProject.java_version.toInteger()
    }

    publishing {
        repositories {
            maven {
                url = uri("${rootProject.projectDir}/repo")
            }
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
