org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

java_version=21

# Minecraft Properties
minecraft_version=1.21.1
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
enabled_platforms=fabric,neoforge

# Dependency Versions
neo_version=21.1.200
fabric_loader_version=0.19.2
fabric_api_version=0.116.12+1.21.1
architectury_version=13.0.8
modmenu_version=11.0.4
trinkets_version=3.10.0

# ToucanLib
useLocalToucanLib=false
toucanlib_version=0.3.0
toucanlib_modrinth_slug=toucan
toucanlib_fabric_version=0.3.0-fabric
toucanlib_neoforge_version=0.3.0-neoforge
toucanlib_curse_project_id=1542666
toucanlib_curse_file_id=8089151

# Loader Ranges
minecraft_version_range=[1.21.1]
loader_version_range=[1,)

## Mod Properties
mod_id=emeraldpouch
mod_name=Emerald Pouch
mod_authors=jvn
mod_license=GNU General Public License v3.0
mod_version=1.0.2
maven_group=com.jvn.emeraldpouch
mod_description=Portable emerald-only storage pouches with auto compact and auto pickup toggles.
mod_display_url=https://modrinth.com/mod/emerald-pouch
mod_issue_tracker=https://github.com/JevenDev/Emerald-Pouch/issues
