modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
# issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
# logoFile="logo.png"
authors="jvn"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
description='''
Portable emerald-only storage pouches with auto compact and auto pickup toggles.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="shulkerboxtooltip"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="curios"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="accessories"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
